GET https://lectortmo-api.herokuapp.com/lectortmo-api/mangas

###

POST https://lectortmo-api.herokuapp.com/user/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}

###

POST https://lectortmo-api.herokuapp.com/lectortmo-api/user/register
Content-Type: application/json

{
  "username": "test",
  "email": "test@test.com",
  "password": "12345678"
}

###

POST https://lectortmo-api.herokuapp.com/lectortmo-api/manhwas/upload/5f6fe48bcc13a524682e6fbd
Content-Type: application/json

{
  "title": "New world3",
  "description": "Se ve weno",
  "imageURL": "https://otakuteca.com/images/books/cover/5e711702ab21c.jpg",
  "type": "Manhwa",
  "demography": "Seinen",
  "status": "En progreso",
  "tags": ["Ecchi", "Romance", "Comedia"]
}


###

PATCH https://lectortmo-api.herokuapp.com/manhwas/5f651c9630328119891ac0c5/5f715172476e716557b2f644
Content-Type: application/json
Cookie: auth_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjczZjU5OTY4ODExMzI4NDQ2NTFlZGYiLCJpYXQiOjE2MDE1MjU4OTd9.35HyFu4BZClOdi86R-fW1kA_cDvp1GjChMW0tJFYJe4; Max-Age=3; Path=/; Expires=Thu, 01 Oct 2020 04:18:20 GMT; HttpOnly

{
  "rating": 10.00
}

###

DELETE https://lectortmo-api.herokuapp.com/lectortmo-api/manhwas/5f6fe53bcc13a524682e6fbe/5f6fe48bcc13a524682e6fbd
